name: "autopy-lot"
author: deep5050
description: "Converts Jupyter Notebooks to python, Markdown ,rmarkdown and lot more !"

inputs:
  github_token:
    description: "GITHUB_TOKEN secret < automatically provided by Github , you don't need to set up >"
    required: true

  check:
    description: "Which files to check: all or just committed: all | latest"
    default: "all"
    required: false

  input_type:
    description: "File types to be converted : py | ipynb | r "
    default: "ipynb"
    required: false

  comment_magics:
    description: "--opt comment_magics <see documentation> : false (default) | true "
    default: ""
    required: false

  split_at_heading:
    description: "--opt split_at_heading <see documentation> :false (default) | true"
    default: ""
    required: false

  output_type:
    description: "Target output type: py | markdown | rmarkdown | r | ipynb"
    default: "py"
    required: false

    output_dir:
      description: "Output directory"
      default: './autopy-lot/'
      required: true


  target_branch:
    description: "Branch that the badge will target. Defaults to the current branch."
    default: ""
    required: false

  pull_request_branch:
    description: "Branch that the badge will target on pull_request. Defaults to GITHUB_BASE_REF."
    default: ""
    required: false

  target_repository:
    description: "Repository that the badge will target. Defaults to the current repository."
    default: ""
    required: false

  pull_request_repository:
    description: "Repository that the badge will target on pull_request. Defaults to TARGET_REPOSITORY"
    default: ""
    required: false

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "chevron-right"
  color: "green"
